name: Lint and Auto Merge
on:
  push:
    branches:
      - 'feature/*'
jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20
      - name: Install Node.js dependencies
        run: npm ci
      - name: Run linters
        uses: wearerequired/lint-action@v2.3.0
        with:
          eslint: true
          prettier: true
  auto-merge:
    needs: run-linters
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
      - name: Auto-merge feature branch into main
        uses: pascalgn/automerge-action@v0.15.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mergeMethod: squash
          branch: main
      - name: Delete feature branch after merge
        run: |
          git branch -d ${{ github.ref_name }}
          git push origin --delete ${{ github.ref_name }}